### PR TITLE
add sign-in and create new accounts with google.

### PR DESCRIPTION
**Pull request by pmclain**
This integration includes new account creation and signin for existing users. Found a much smaller Google Oauth client removing almost all bloat from the previous iteration.

### CODE REVIEW

**Comment by pmclain** [comment]
this commit does not include edits to core.update.php needed for adding the new options during upgrade.

**Comment by ignacionelson** [comment]
Awesome! Let's keep improving this, it's a great addition!

One thing that needs to be replaced is the password generating function on the class ClientActions, as it's not really random and therefore secure.

**Comment by pmclain** [comment]
Thanks. I opened issue #176 noting the issue with the password generation method.

**Comment by ignacionelson** [comment]
I've implemented paragonie's random_compat to fix this.
I believe that the next step is to improve on the callback file which seems to have more than it actually needs. And probably make it so it can be reused by other social networks.

Please update from the master branch to get the changes I made.

**Pull request merged**
