### PR TITLE
Google Sign In for existing users

### PR DESCRIPTION
**Pull request by pmclain**
Gives existing accounts the ability to login using their Google accounts. Feature is very limited to test desirability of social login. Further development would benefit from creation of user class to remove repetitive code blocks.

### CODE REVIEW

**Comment by ignacionelson** [comment]
This is awesome!

**Comment by ignacionelson** [comment]
Wondering if it would be better to directly include the full v1 package instead of relying on composer. For people downloading the master from github instead of the release from the site, this would prevent them from using it as the library is not included.

Also, didn't check before but the api bumps up the size of the projectsend release zip file by a lot sadly. Not a problem, but... :(

**Comment by ignacionelson** [comment]
Sorry for the revert. I merged by mistake and had to go back. Please let's keep working on this, it's a great feature!

**Comment by pmclain** [comment]
Glad you like the idea. I'll keep building this out. I included the full Google API client to avoid a dependency on composer. I will look for an alternative to the official Google API client, https://github.com/google/google-api-php-client/releases. The has to be a lighter client somewhere that can be used strictly for user authentication.

**Pull request merged**
