### PR TITLE
New options to control news and new version check

### PR DESCRIPTION
**Pull request by orouet**

### CODE REVIEW

**Comment by ignacionelson** [comment]
Nice! Thanks for doing these changes!
Sorry to ask, but is there a chance you can apply them to the newest file versions? I can't merge since some of the files are old and had changes not reflected on this PR.

**Comment by orouet** [comment]
Of course ! I'm on the way

**Comment by ignacionelson** [comment]
youre-awesome

**Comment by ignacionelson** [comment]
The latest PR only has the config file changed. Is it by mistake or because the other files are not ready yet?

**Pull request closed without merging**
