### PR TITLE
NEW: added handy debug info during install phase

### PR DESCRIPTION
**Pull request by paspo**
Now it's easy to know actual PHP version and MySQL PDO driver status.
This should help non-tech users when asking for help.

### CODE REVIEW

**Comment by lenamtl** [comment]
Thanks

**Comment by paspo** [comment]
On second thought, the database object ($dbh) is initialized every time, and this is the cause of the majority of "blank page" errors. 

( no PDO, so $dbh is null at includes/classes/database.php:17, and in includes/site.options.php:18 and error is generated, but it's suppressed because of sys.vars.php:33 )

I think a check like sys.vars.php:56 is needed, to guarantee that PDO is ok.

**Comment by lenamtl** [comment]
Hi I have merge your pulled request
try to install on my localhost
The install page is blank

**Comment by paspo** [comment]
To debug, let's start by commenting line 33 in sys.vars.php  ( error_reporting(0); is for disabling any debug output)
Then retry and post the error here.

**Comment by lenamtl** [comment]
Strict standards: Declaration of PDOEx::prepare() should be compatible with PDO::prepare($statement, $options = NULL) in .... on line 55

Fatal error: Call to a member function query() on a non-object in ...projectsend\includes\site.options.php on line 18

**Comment by paspo** [comment]
PHP version? os version?

**Comment by lenamtl** [comment]
PHP 5.5.12
MySQL 5.6.17
Wampserver on Windows7
I'm using PDO  with all my custom applications

**Comment by paspo** [comment]
I've just tried your setup in a Win7-64 VM.
- Downloaded latest Wampserver from http://www.wampserver.com/en/
- Downloaded and installed VCRedist (9, 10, 11, 13 and 14; 32bit AND 64bit versions, for all of them; seriously these requirements are a real nightmare)
- installed Wampserver
- created the DB
- downloaded latest zip from master (r610)
- unzipped and created sys.config.php
-> everything works

Any clue on how to reproduce the issue?

**Comment by lenamtl** [comment]
Hi,
I have cleared all my previous projectsend installation and start from scratch.
I was able to install it it no problem, so I thought I probably made a stupid typo error in my db connection...

I made some tests to reproduce the case.  
Fisrt test I have entered wrong db name and correct login info and I got both errors:

Strict standards: Declaration of PDOEx::prepare() should be compatible with PDO::prepare($statement, $options = NULL) in .... projectsend\includes\classes\database.php on line 55

Fatal error: Call to a member function query() on a non-object in ...projectsend\includes\site.options.php on line 18

Then I have use an existing projectsend database and filled with data so Projectsend is already installed and you go to /install page
I have this error;
Strict standards: Declaration of PDOEx::prepare() should be compatible with PDO::prepare($statement, $options = NULL) in .... projectsend\includes\classes\database.php on line 55

These error message should be fixed to display understandable error message to the user....

**Pull request merged**
