### PR TITLE
Correct MySql Syntax Error During Some Installations

### LINKED ISSUE #136: PDOExceptions after /install/index.php
I´m trying to get projectsend r608/609 to work.
OS: ubuntu 16.04 LTS
php7 and php5.6 tested.
phpinfo() is ok, database user and login seems to be ok (no errors in mysql logs), pdo is also enabled (tried a fix from a pull request)
image
after filling all basic informations and pressing the install-button I always get this:
image
I´ve got no further ideas, what I´m doing wrong. Can someone please have a look at this and give me an hint?
Thanks.

### PR DESCRIPTION
**Pull request by pmclain**
Resolve #136. Add default value to TABLE_FILES.`expiry_date`. The lack of default value was causing syntax error during the install script.

### CODE REVIEW

**Comment by pmclain** [comment]
Resolve #167 Added option to jQuery.tagsInput allow class declaration on fakeInput. Set fakeInputClass option in options.php to empty allowing form validation.

**Comment by ignacionelson** [comment]
Thanks for your work!! I'd like to merge the db change but can't do it without the other one and I wonder about the tags input change. I would prefer not to modify the dist js file of the input tags script, as that would backfire if we need to update it later. Also, the default js validation takes this field into account (since a commit from yesterday).
Is there any particular reason for this change?

**Comment by pmclain** [comment]
No particular reason for the changes to the input tags script. I missed the commit from yesterday with the fix. I've removed those changes from the pull request. Glad to help!

**Comment by pmclain** [comment]
Ok. The first commit to revert was not correct. Should be ready now. Sorry for the cluttered commits.

**Comment by ignacionelson** [comment]
Done, thanks again!

**Pull request merged**
